[parity]
keys_path = "/app/keys"
chain = "/app/chain.json"
auto_update = "none"

[network]
discovery = false
min_peers = 0

[rpc]
cors = ["all"]
apis = ["eth","net","private","parity","personal"] 
interface = "all"

[ui]
disable = true

[account]
unlock = [ '0x55Ba0aDE49583cE6a907eC6dd75A9E2B559756A5',
           '0xeBfD1a5391130d58282a2943681aA549cf2B6035',
           '0xef950F7361262D1617Ab2190C80bB0B750fD0481' ]
password = ["/app/password.pwds"]

[mining]
engine_signer = "0xeBfD1a5391130d58282a2943681aA549cf2B6035"
author = "0xeBfD1a5391130d58282a2943681aA549cf2B6035"
reseal_on_txs = "none"
force_sealing = true

[misc]
logging = "own_tx=trace"
